/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author nurfebrianabakri
 */
public class Homepage extends javax.swing.JFrame {

    /**
     * Creates new form Homepage
     */
    public Homepage() {
        initComponents();
    }
    
 
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        Homepage = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Sumatera = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Homepage.setBackground(new java.awt.Color(123, 96, 89));
        Homepage.setForeground(new java.awt.Color(255, 255, 255));
        Homepage.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bunga.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        Homepage.add(jLabel1);
        jLabel1.setBounds(0, 0, 130, 120);

        jLabel2.setFont(new java.awt.Font("ITF Devanagari", 0, 30)); // NOI18N
        jLabel2.setText("Explore the ");
        Homepage.add(jLabel2);
        jLabel2.setBounds(20, 60, 190, 46);

        jLabel3.setFont(new java.awt.Font("ITF Devanagari", 0, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(148, 60, 2));
        jLabel3.setText("Beautiful Indonesia");
        Homepage.add(jLabel3);
        jLabel3.setBounds(20, 100, 290, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ic_baseline-search.png"))); // NOI18N
        Homepage.add(jLabel4);
        jLabel4.setBounds(210, 140, 30, 30);

        jTextField1.setBackground(new java.awt.Color(142, 84, 69));
        jTextField1.setForeground(new java.awt.Color(224, 201, 194));
        jTextField1.setText("Search here");
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        Homepage.add(jTextField1);
        jTextField1.setBounds(40, 140, 180, 30);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Group 2.png"))); // NOI18N
        Homepage.add(jLabel16);
        jLabel16.setBounds(20, 130, 250, 50);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/komhome1.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        Homepage.add(jLabel6);
        jLabel6.setBounds(0, -20, 400, 250);

        Sumatera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SUMATERA.png"))); // NOI18N
        Sumatera.setText("jLabel8");
        Sumatera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SumateraMouseClicked(evt);
            }
        });
        Homepage.add(Sumatera);
        Sumatera.setBounds(0, 230, 100, 100);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PAPUA.png"))); // NOI18N
        Homepage.add(jLabel9);
        jLabel9.setBounds(310, 230, 110, 116);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NTB.png"))); // NOI18N
        Homepage.add(jLabel10);
        jLabel10.setBounds(210, 350, 50, 30);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MALUKU.png"))); // NOI18N
        Homepage.add(jLabel11);
        jLabel11.setBounds(230, 280, 110, 60);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MALUKU UTARA.png"))); // NOI18N
        Homepage.add(jLabel12);
        jLabel12.setBounds(260, 240, 40, 60);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/KALIMANTAN.png"))); // NOI18N
        Homepage.add(jLabel13);
        jLabel13.setBounds(70, 220, 120, 120);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SULAWESI.png"))); // NOI18N
        Homepage.add(jLabel15);
        jLabel15.setBounds(130, 190, 187, 200);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NTT.png"))); // NOI18N
        Homepage.add(jLabel17);
        jLabel17.setBounds(250, 330, 60, 80);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JAWA.png"))); // NOI18N
        Homepage.add(jLabel18);
        jLabel18.setBounds(70, 320, 130, 60);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BALI.png"))); // NOI18N
        Homepage.add(jLabel14);
        jLabel14.setBounds(180, 350, 56, 40);

        jPanel3.setBackground(new java.awt.Color(255, 248, 240));
        jPanel3.setLayout(null);

        jLabel5.setFont(new java.awt.Font("ITF Devanagari", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(148, 60, 2));
        jLabel5.setText("Popular City");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(20, 10, 100, 30);

        jPanel1.setBackground(new java.awt.Color(255, 248, 240));
        jPanel1.setLayout(null);
        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(0, 170, 520, 10);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Rectangle 25.png"))); // NOI18N
        jPanel1.add(jLabel20);
        jLabel20.setBounds(20, 0, 191, 174);

        jScrollPane5.setViewportView(jPanel1);

        jPanel3.add(jScrollPane5);
        jScrollPane5.setBounds(130, 130, 220, 170);
        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(390, 0, 10, 270);

        Homepage.add(jPanel3);
        jPanel3.setBounds(0, 390, 400, 330);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        Homepage.add(jPanel2);
        jPanel2.setBounds(0, 0, 100, 100);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Homepage, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Homepage, javax.swing.GroupLayout.DEFAULT_SIZE, 663, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SumateraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SumateraMouseClicked
        // TODO add your handling code here: ini itu sumatera kalau di klik
    }//GEN-LAST:event_SumateraMouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Homepage;
    private javax.swing.JLabel Sumatera;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
